
name: Python Build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install --no-interaction
      - name: Package Build
        run: |
          poetry build
      - name: Package Publish
        run: |
          poetry config repositories.azure https://pkgs.dev.azure.com/takshimizu/_packaging/myPackage/pypi/upload/ --local
          poetry config http-basic.azure tmp_token ${{ secrets.AZURE_DEVOPS_SECRET }} --local
          poetry publish -r azure
