name: Package Build

on:
  pull_request:
    branches: "main"
  types: closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      python-version: 3.12
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install --no-interaction
      - name: Package Build
        run: |
          poetry build
      - name: Package Publish
        run: |
          poetry config repositories.azure https://pkgs.dev.azure.com/takshimizu/_packaging/myPackage/pypi/upload/ --local
          poetry config http-basic.azure tmp_token ${{ secrets.AZURE_DEVOPS_SECRET }} --local
          poetry publish -r azure
