
name: Python Build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        env:
          SUPER_SECRET: ${{ secrets.AZURE_DEVOPS_SECRET }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install --no-interaction
      - name: Pack Build
        run: |
          poetry build
          poetry self add artifacts-keyring
      - name: Pack publish
        run: |
          echo ${{ secrets.SAMPLE_SECRETS }}
          poetry config http-basic.azure tmp_token "::add-mask::${{ env.SUPER_SECRET }}" --local
          poetry config repositories.azure https://pkgs.dev.azure.com/takshimizu/_packaging/mySamplePack/pypi/upload/ --local
          poetry publish -r azure
